import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import AppPromo from "@/components/AppPromo";
import Footer from "@/components/Footer";
import FaqSection from "@/components/FaqSection";
import ReviewSlider from "@/components/ReviewSlider";

// database connection setup
import "@/lib/initDb"; // will run dbConnect() when the app starts
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased mb-4`}
      >
        <div className="">
          <Toaster position="top-right" />
          <Header />
          {children}

          <ReviewSlider />
          <FaqSection />
          {/* <AppPromo /> */}
          <Footer />
        </div>
      </body>
    </html>
  );  
}
